<?php
//if( function_exists('acf_add_local_field_group') ):
//
//	acf_add_local_field_group(array(
//		'key' => 'group_605f69905c0e1',
//		'title' => 'Configuração ebook',
//		'fields' => array(
//			array(
//				'key' => 'field_605f6aaae246d',
//				'label' => 'Descrição do ebook',
//				'name' => 'descricao_do_ebook',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_605f69f1564e2',
//				'label' => 'Tipo de download de arquivo',
//				'name' => 'tipo_de_download_de_arquivo',
//				'type' => 'radio',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'formulario' => 'Abrir formulário interno',
//					'link' => 'Linkar para página externa',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_605f6a44564e3',
//				'label' => 'Inserir o formulário',
//				'name' => 'inserir_o_formulario',
//				'type' => 'text',
//				'instructions' => 'Caso nenhum formulário seja inserido será utilizado o formulário padrão',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_605f69f1564e2',
//							'operator' => '==',
//							'value' => 'formulario',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605f6a6d564e4',
//				'label' => 'Link externo',
//				'name' => 'link_externo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_605f69f1564e2',
//							'operator' => '==',
//							'value' => 'link',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'ebooks',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_60592eeb5e2ec',
//		'title' => 'Conteúdos relacionados',
//		'fields' => array(
//			array(
//				'key' => 'field_605f61a9883a0',
//				'label' => 'Header página',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605f61c1883a1',
//				'label' => 'Titulo',
//				'name' => 'titulo_header_pagina',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605f61d5883a2',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo_header_pagina',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_60592f13aa282',
//				'label' => 'Soluções relacionadas',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_60592ef7aa281',
//				'label' => 'escolher_solucoes',
//				'name' => 'escolher_solucoes',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'solucoes',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//				),
//				'elements' => '',
//				'min' => '',
//				'max' => '',
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_60592f36aa283',
//				'label' => 'Conteúdo relacionado',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_60592f4aaa284',
//				'label' => 'Escolher conteúdos',
//				'name' => 'escolher_conteudos',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'post',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//				),
//				'elements' => '',
//				'min' => '',
//				'max' => '',
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_605931c6aa287',
//				'label' => 'Pree footer',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_60593211aa288',
//				'label' => 'Titulo',
//				'name' => 'titulo_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6059321eaa289',
//				'label' => 'Descrição',
//				'name' => 'descricao_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6059322faa28a',
//				'label' => 'Tipo de CTA',
//				'name' => 'tipo_de_cta',
//				'type' => 'radio',
//				'instructions' => 'Escolhe o tipo de CTA que será utilizado
//
//Modal: abrirá um formulário
//Link: poderá direcionar o usuário para qualquer local em nova página',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'modal' => 'Abrir um formulário em modal',
//					'link' => 'Direcionar o usuário para página de contato ou contato externo',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_60593257aa28b',
//				'label' => 'Direcionamento',
//				'name' => 'direcionamento',
//				'type' => 'url',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_6059322faa28a',
//							'operator' => '==',
//							'value' => 'link',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'projeto',
//				),
//			),
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'page',
//				),
//			),
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'post',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_6059d7451b15c',
//		'title' => 'Depoimentos',
//		'fields' => array(
//			array(
//				'key' => 'field_6059d74cfc8d6',
//				'label' => 'Depoimento',
//				'name' => 'depoimento',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_6059d75ffc8d7',
//				'label' => 'Profissional',
//				'name' => 'profissional',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6059d770fc8d8',
//				'label' => 'Cargo',
//				'name' => 'cargo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'clientes',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_605bbdbbaf445',
//		'title' => 'Home site',
//		'fields' => array(
//			array(
//				'key' => 'field_605bc05368f59',
//				'label' => 'Banner',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605bbf7fe2d7f',
//				'label' => 'Banner principal',
//				'name' => 'banner_principal',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => '',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'block',
//				'button_label' => '',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_605bbfe2e2d80',
//						'label' => 'Imagem',
//						'name' => 'imagem_banner',
//						'type' => 'image',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'url',
//						'preview_size' => 'medium',
//						'library' => 'all',
//						'min_width' => '',
//						'min_height' => '',
//						'min_size' => '',
//						'max_width' => '',
//						'max_height' => '',
//						'max_size' => '',
//						'mime_types' => '',
//					),
//					array(
//						'key' => 'field_605bbff4e2d81',
//						'label' => 'Titulo',
//						'name' => 'titulo_banner',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_605bc02be2d82',
//						'label' => 'Texto CTA',
//						'name' => 'cta',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_605bc03ae2d83',
//						'label' => 'Link CTA',
//						'name' => 'link_cta',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_605bc316dc843',
//				'label' => 'Sobre',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605bc35cdc844',
//				'label' => 'Titulo sobre',
//				'name' => 'titulo_sobre',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bc36ddc845',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo_sobre',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bc375dc846',
//				'label' => 'Descrição',
//				'name' => 'descricao_sobre',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_605bc5811c63e',
//				'label' => 'Soluções',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605bc5921c63f',
//				'label' => 'Titulo',
//				'name' => 'titulo_solucoes',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bc5b01c640',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bc5c21c641',
//				'label' => 'descricao',
//				'name' => 'descricao_solucao',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bc6925602b',
//				'label' => 'CTA soluções',
//				'name' => 'cta_solucoes',
//				'type' => 'url',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_605bcd9aed57e',
//				'label' => 'Video',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605bce91ed57f',
//				'label' => 'Titulo',
//				'name' => 'titulo_video',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bcea4ed580',
//				'label' => 'sub titulo',
//				'name' => 'sub_titulo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605bced8ed581',
//				'label' => 'Youtube video',
//				'name' => 'youtube_video',
//				'type' => 'oembed',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'width' => '',
//				'height' => '',
//			),
//			array(
//				'key' => 'field_605c91bf67c42',
//				'label' => 'Blog header',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605c91dd67c43',
//				'label' => 'Titulo',
//				'name' => 'titulo_blog_home',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605c91e667c44',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo_blog_home',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605f46b156070',
//				'label' => 'Ativar destaque na página de blog',
//				'name' => 'ativar_destaque_na_pagina_de_blog',
//				'type' => 'true_false',
//				'instructions' => 'Esta opção irá adicionar um destaque de blog posts no header da página de blog',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'message' => 'Deseja ativar destaque',
//				'default_value' => 0,
//				'ui' => 0,
//				'ui_on_text' => '',
//				'ui_off_text' => '',
//			),
//			array(
//				'key' => 'field_605f46589f010',
//				'label' => 'Blog destaque',
//				'name' => 'blog_destaque',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'post',
//				),
//				'taxonomy' => '',
//				'filters' => '',
//				'elements' => array(
//					0 => 'featured_image',
//				),
//				'min' => '',
//				'max' => 3,
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_605c928240052',
//				'label' => 'Clientes',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605c92b640053',
//				'label' => 'Titulo',
//				'name' => 'titulo_clientes_home',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605c92c640054',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo_clientes_home',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605c92e940055',
//				'label' => 'Descrição',
//				'name' => 'descricao_clientes_home',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_605c9ced88b07',
//				'label' => 'Prova social',
//				'name' => 'prova_social',
//				'type' => 'radio',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'depoimento' => 'Slider de depoimentos',
//					'projetos' => 'Slider de projetos',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_605e5175cd10d',
//				'label' => 'Pré footer',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_605e519bcd10e',
//				'label' => 'Titulo',
//				'name' => 'titulo_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605e51a8cd10f',
//				'label' => 'Descrição',
//				'name' => 'descricao_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605e51b4cd110',
//				'label' => 'Tipo de CTA',
//				'name' => 'tipo_de_cta',
//				'type' => 'radio',
//				'instructions' => 'Escolhe o tipo de CTA que será utilizado
//
//Modal: abrirá um formulário
//Link: poderá direcionar o usuário para qualquer local em nova página',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'modal' => 'Abrir um formulário em modal',
//					'link' => 'Direcionar o usuário para página de contato ou contato externo',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_605e51dccd111',
//				'label' => 'Direcionamento',
//				'name' => 'direcionamento',
//				'type' => 'url',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_605e51b4cd110',
//							'operator' => '==',
//							'value' => 'link',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_605e555bbce2e',
//				'label' => 'Imagem',
//				'name' => 'imagem_pre_footer',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'options_page',
//					'operator' => '==',
//					'value' => 'home',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_60560bfb9f634',
//		'title' => 'Icone',
//		'fields' => array(
//			array(
//				'key' => 'field_60560c0dcf73c',
//				'label' => 'Icone',
//				'name' => 'icone_item',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'solucoes',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'side',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_6053df7e5b101',
//		'title' => 'Configuração da solução',
//		'fields' => array(
//			array(
//				'key' => 'field_6053e1140092d',
//				'label' => 'Header',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e02341837',
//				'label' => 'Descrição',
//				'name' => 'descricao_header',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_6053e1ca87409',
//				'label' => 'Outras conexões',
//				'name' => 'outros_itens_do_header',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'block',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_6053e04441838',
//						'label' => 'Texto CTA',
//						'name' => 'texto_cta',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_6053e05441839',
//						'label' => 'Tipo de link',
//						'name' => 'tipo_de_link',
//						'type' => 'radio',
//						'instructions' => 'Escolha o tipo de link se externo ou interno do site
//Obs: caso o link seja externo, abrirá em uma nova aba.',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'interno' => 'Link para uma página interna',
//							'externo' => 'Link para uma página externa',
//						),
//						'allow_null' => 0,
//						'other_choice' => 0,
//						'default_value' => '',
//						'layout' => 'horizontal',
//						'return_format' => 'value',
//						'save_other_choice' => 0,
//					),
//					array(
//						'key' => 'field_6053e1501925b',
//						'label' => 'Link interno',
//						'name' => 'link_interno',
//						'type' => 'page_link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_6053e05441839',
//									'operator' => '==',
//									'value' => 'interno',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'post_type' => '',
//						'taxonomy' => '',
//						'allow_null' => 0,
//						'allow_archives' => 1,
//						'multiple' => 0,
//					),
//					array(
//						'key' => 'field_6053e26003e31',
//						'label' => 'Link externo',
//						'name' => 'link_externo',
//						'type' => 'url',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_6053e05441839',
//									'operator' => '==',
//									'value' => 'externo',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_6053e31ab63ec',
//				'label' => 'Escopo',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e325b63ed',
//				'label' => 'Titulo',
//				'name' => 'titulo_escopo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6053e330b63ee',
//				'label' => 'Sub titulo',
//				'name' => 'sub_titulo_escopo',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '50',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_605f4dff451e5',
//				'label' => 'Descrição',
//				'name' => 'descricao_escopo',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'visual',
//				'toolbar' => 'full',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_6053e45f7e14b',
//				'label' => 'Tipo de bloco',
//				'name' => 'tipo_de_bloco',
//				'type' => 'radio',
//				'instructions' => 'Escolha a forma como deseja apresentar o escopo',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'texto' => 'Combinado de textos e imagem',
//					'imagem' => 'Utilize uma imagem para ilustrar o escopo',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_6053e340b63ef',
//				'label' => 'Adicionar item',
//				'name' => 'adicionar_item',
//				'type' => 'repeater',
//				'instructions' => 'Adiciona um novo step ao escopo',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_6053e45f7e14b',
//							'operator' => '==',
//							'value' => 'texto',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => '',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'row',
//				'button_label' => '',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_6053e368b63f0',
//						'label' => 'Titulo',
//						'name' => 'titulo_step_escopo',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_6053e384b63f1',
//						'label' => 'Descrição',
//						'name' => 'descricao_step_escopo',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_6053e394b63f2',
//						'label' => 'Icone',
//						'name' => 'icone',
//						'type' => 'image',
//						'instructions' => 'Não obrigatório, aparecerá o circulo laranja',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'url',
//						'preview_size' => 'medium',
//						'library' => 'all',
//						'min_width' => '',
//						'min_height' => '',
//						'min_size' => '',
//						'max_width' => '',
//						'max_height' => '',
//						'max_size' => '',
//						'mime_types' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_6053e4b57e14c',
//				'label' => 'Fluxo de escopo',
//				'name' => 'fluxo_de_escopo',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_6053e512bcb62',
//				'label' => 'Beneficios',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e8b6086c3',
//				'label' => 'Configuração de posição',
//				'name' => 'configuracao_de_posicao',
//				'type' => 'radio',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'left' => 'Posicionar a imagem a esquerda',
//					'right' => 'posicionar a imagem a direita',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_6053e932515b9',
//				'label' => 'Informações sobre os beneficio',
//				'name' => 'informacoes_sobre_os_beneficio',
//				'type' => 'group',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '60',
//					'class' => '',
//					'id' => '',
//				),
//				'layout' => 'row',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_6053e524bcb63',
//						'label' => 'Titulo',
//						'name' => 'titulo_beneficio',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_6053e52cbcb64',
//						'label' => 'Titpo de texto',
//						'name' => 'titpo_de_texto_beneficio',
//						'type' => 'radio',
//						'instructions' => 'Utilize este botão para escolher o formato de texto',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'texto' => 'Texto corrido',
//							'topicos' => 'Tópicos',
//						),
//						'allow_null' => 0,
//						'other_choice' => 0,
//						'default_value' => '',
//						'layout' => 'horizontal',
//						'return_format' => 'value',
//						'save_other_choice' => 0,
//					),
//					array(
//						'key' => 'field_6053e5b0bcb65',
//						'label' => 'Texto corrido',
//						'name' => 'texto_corrido_beneficio',
//						'type' => 'wysiwyg',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_6053e52cbcb64',
//									'operator' => '==',
//									'value' => 'texto',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'tabs' => 'visual',
//						'toolbar' => 'full',
//						'media_upload' => 1,
//						'delay' => 0,
//					),
//					array(
//						'key' => 'field_6053e5cbbcb66',
//						'label' => 'Tópicos',
//						'name' => 'topicos_beneficio',
//						'type' => 'repeater',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => array(
//							array(
//								array(
//									'field' => 'field_6053e52cbcb64',
//									'operator' => '==',
//									'value' => 'topicos',
//								),
//							),
//						),
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'collapsed' => '',
//						'min' => 0,
//						'max' => 0,
//						'layout' => 'block',
//						'button_label' => '',
//						'sub_fields' => array(
//							array(
//								'key' => 'field_6053e600bcb67',
//								'label' => 'Titulo',
//								'name' => 'titulo_topico',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//							array(
//								'key' => 'field_6053e609bcb68',
//								'label' => 'Descrição do tópico',
//								'name' => 'descricao_do_topico',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//						),
//					),
//				),
//			),
//			array(
//				'key' => 'field_6053e889086c2',
//				'label' => 'Imagem',
//				'name' => 'imagem_beneficio',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '40',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_6053e63b6824f',
//				'label' => 'Soluções relacionadas',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e64768250',
//				'label' => 'Escolher soluções',
//				'name' => 'escolher_solucoes',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'solucoes',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//				),
//				'elements' => '',
//				'min' => '',
//				'max' => 6,
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_6053e720e43a7',
//				'label' => 'Conteúdo relacionado',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e730e43a8',
//				'label' => 'Escolher conteúdos',
//				'name' => 'escolher_conteudos',
//				'type' => 'relationship',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'post_type' => array(
//					0 => 'post',
//				),
//				'taxonomy' => '',
//				'filters' => array(
//					0 => 'search',
//				),
//				'elements' => '',
//				'min' => '',
//				'max' => '',
//				'return_format' => 'object',
//			),
//			array(
//				'key' => 'field_6053e79dea841',
//				'label' => 'Pré footer',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_6053e7a7ea842',
//				'label' => 'Titulo',
//				'name' => 'titulo_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6053e7c8ea843',
//				'label' => 'Descrição',
//				'name' => 'descricao_pre_footer',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6053e7d2ea844',
//				'label' => 'Tipo de CTA',
//				'name' => 'tipo_de_cta',
//				'type' => 'radio',
//				'instructions' => 'Escolhe o tipo de CTA que será utilizado
//
//Modal: abrirá um formulário
//Link: poderá direcionar o usuário para qualquer local em nova página',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'choices' => array(
//					'modal' => 'Abrir um formulário em modal',
//					'link' => 'Direcionar o usuário para página de contato ou contato externo',
//				),
//				'allow_null' => 0,
//				'other_choice' => 0,
//				'default_value' => '',
//				'layout' => 'horizontal',
//				'return_format' => 'value',
//				'save_other_choice' => 0,
//			),
//			array(
//				'key' => 'field_6053e84eea845',
//				'label' => 'Direcionamento',
//				'name' => 'direcionamento',
//				'type' => 'url',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => array(
//					array(
//						array(
//							'field' => 'field_6053e7d2ea844',
//							'operator' => '==',
//							'value' => 'link',
//						),
//					),
//				),
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//			),
//			array(
//				'key' => 'field_605e55862f174',
//				'label' => 'Imagem',
//				'name' => 'imagem_pre_footer',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'medium',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'solucoes',
//				),
//			),
//		),
//		'menu_order' => 1,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//endif;