<?php
get_header();
    get_template_part('parts/home/home-banner');
    get_template_part('parts/home/home-menu-control');
    get_template_part('parts/home/home-about');
    get_template_part('parts/home/home-qualidade');
    get_template_part('parts/home/home-video');
    get_template_part('parts/home/home-blog');
    get_template_part('parts/home/home-clientes');
    get_template_part('parts/home/home-depoimentos');
    get_template_part('parts/footer/footer-pre-footer-img');
get_footer();